#pragma once

#include "CoreMinimal.h"
#include "Subsystems/WorldSubsystem.h"
#include "ZeusEntityTypes.h"
#include "ZeusWorldSubsystem.generated.h"

class AActor;
class AZeusCharacter;
class AZeusPlayerProxy;
class UZeusNetworkSubsystem;

/**
 *  UZeusWorldSubsystem
 *
 *  Subsistema por-mundo que orquestra a aplicacao de pacotes de replicacao
 *  recebidos do servidor (`S_SPAWN_PLAYER`, `S_DESPAWN_PLAYER`,
 *  `S_PLAYER_STATE`) em atores na cena. Mantem um registry
 *  `EntityId -> AActor*` e despacha cada mensagem para o ator correto.
 *
 *  Por que `UWorldSubsystem` (e nao `UGameInstanceSubsystem`)?
 *    - Atores so existem dentro de um `UWorld`. Quando o mapa troca, este
 *      registry e descartado naturalmente — sem leak de ponteiros para
 *      atores do mundo anterior.
 *    - O `UZeusNetworkSubsystem` (per-game-instance) continua dono da
 *      conexao UDP e dos delegates; este subsistema apenas escuta os
 *      delegates e materializa atores na cena atual.
 *
 *  Resolucao de classe por `EZeusEntityType`:
 *    - `RemoteEntityClasses` e um TMap configuravel (BlueprintReadWrite)
 *      com defaults seguros em `Initialize`. Permite trocar
 *      `AZeusPlayerProxy` por um BP filho com mesh customizada sem
 *      recompilar C++.
 *
 *  Despawn:
 *    - V0: chama `IZeusEntityInterface::SetEntityRelevant(false)` (preserva
 *      o ator para futuro pooling).
 *    - V1: pool real por `EntityType`, limites de memoria, expiracao.
 */
UCLASS()
class ZMMO_API UZeusWorldSubsystem : public UWorldSubsystem
{
	GENERATED_BODY()

public:
	virtual void Initialize(FSubsystemCollectionBase& Collection) override;
	virtual void OnWorldBeginPlay(UWorld& InWorld) override;
	virtual void Deinitialize() override;

	/**
	 *  Regista o jogador local no registry. Chamado por `AZeusCharacter`
	 *  apos receber o `EntityId` autoritativo do servidor (delegate
	 *  `OnPlayerSpawned` com `bIsLocal=true`).
	 */
	UFUNCTION(BlueprintCallable, Category = "Zeus|World")
	void RegisterLocalEntity(int64 EntityId, AActor* LocalActor);

	/** Numero de entidades remotas actualmente trackeadas. Util em debug overlays. */
	UFUNCTION(BlueprintPure, Category = "Zeus|World")
	int32 GetTrackedEntityCount() const { return RemoteEntities.Num(); }

protected:
	/**
	 *  Mapa configuravel de classe a usar por `EZeusEntityType`. Caso vazio,
	 *  usamos defaults seguros (`AZeusPlayerProxy` para Player, `AZeusEntity`
	 *  para Mob/NPC/Object — actualizado quando classes especificas existirem).
	 *
	 *  Pode ser preenchido via Blueprint subclassing ou em runtime.
	 */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Zeus|World")
	TMap<EZeusEntityType, TSubclassOf<AActor>> RemoteEntityClasses;

private:
	UFUNCTION()
	void HandlePlayerSpawned(int64 EntityId, bool bIsLocal, FVector PosCm, float YawDeg, int64 ServerTimeMs);

	UFUNCTION()
	void HandlePlayerDespawned(int64 EntityId);

	UFUNCTION()
	void HandlePlayerStateUpdate(int64 EntityId, int32 InputSeq, FVector PosCm, FVector VelCmS, bool bGrounded, int64 ServerTimeMs);

	UClass* ResolveActorClass(EZeusEntityType EntityType) const;
	UZeusNetworkSubsystem* ResolveZeusNetworkSubsystem() const;

	/**
	 *  Registry de proxies remotos. Chave = `EntityId` autoritativo do servidor.
	 *  Usamos `TWeakObjectPtr` para nao impedir GC se algo der errado e o ator
	 *  for destruido externamente (ex.: troca de mapa).
	 */
	UPROPERTY()
	TMap<int64, TWeakObjectPtr<AActor>> RemoteEntities;

	/** Cached id do jogador local, para ignorar snapshots dele (cliente solto). */
	int64 LocalEntityId = 0;
};
