#pragma once

#include "CoreMinimal.h"
#include "ZMMOEntityTypes.generated.h"

/**
 *  Categoria autoritativa replicada pelo servidor. Determina que classe de ator
 *  o `UZMMOWorldSubsystem` deve spawnar para um snapshot recebido.
 */
UENUM(BlueprintType)
enum class EZMMOEntityType : uint8
{
	Player UMETA(DisplayName = "Player"),
	Mob    UMETA(DisplayName = "Mob"),
	NPC    UMETA(DisplayName = "NPC"),
	Object UMETA(DisplayName = "Object")
};

/**
 *  Snapshot autoritativo aplicado por `IZMMOEntityInterface::ApplyEntitySnapshot`.
 *
 *  Construido pelo `UZMMOWorldSubsystem` a partir dos delegates do
 *  `UZeusNetworkSubsystem` (`OnPlayerStateUpdate` em V0; opcodes para mobs/NPCs
 *  em V1+). Mantemos os campos minimos que o servidor ja replica hoje
 *  (`S_PLAYER_STATE`); novos campos sao adicionados aqui sempre que o protocolo
 *  evoluir, sem mexer nas classes de proxy.
 */
USTRUCT(BlueprintType)
struct FZMMOEntitySnapshot
{
	GENERATED_BODY()

	/** EntityId autoritativo do servidor. */
	UPROPERTY(BlueprintReadOnly, Category = "ZMMO|Entity")
	int64 EntityId = 0;

	/** Categoria do ator (define qual proxy class spawnar). */
	UPROPERTY(BlueprintReadOnly, Category = "ZMMO|Entity")
	EZMMOEntityType EntityType = EZMMOEntityType::Player;

	/** Sequencia de input processada no servidor (so faz sentido para players). */
	UPROPERTY(BlueprintReadOnly, Category = "ZMMO|Entity")
	int32 LastProcessedInputSeq = 0;

	/** Posicao mundo (cm). */
	UPROPERTY(BlueprintReadOnly, Category = "ZMMO|Entity")
	FVector PositionCm = FVector::ZeroVector;

	/** Velocidade mundo (cm/s) — usada para network smoothing e drivers de animacao. */
	UPROPERTY(BlueprintReadOnly, Category = "ZMMO|Entity")
	FVector VelocityCmS = FVector::ZeroVector;

	/** Yaw em graus (orientacao visual). */
	UPROPERTY(BlueprintReadOnly, Category = "ZMMO|Entity")
	float YawDeg = 0.0f;

	/** Indica se o servidor considera o ator em solo. */
	UPROPERTY(BlueprintReadOnly, Category = "ZMMO|Entity")
	bool bGrounded = false;

	/** Tempo do servidor (ms desde epoch) quando este snapshot foi gerado. */
	UPROPERTY(BlueprintReadOnly, Category = "ZMMO|Entity")
	int64 ServerTimeMs = 0;
};
