#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"
#include "GameplayTagContainer.h"
#include "UI/LoadingTypes.h"
#include "UILoadingTipRow.generated.h"

/**
 *  Row do DT_LoadingTips. Cada row = uma dica mostrada (rotaciona durante o
 *  loading). FText é localizável (basta extrair pelo gather de tradução do
 *  UE). Filtra por contexto: Context=None significa "qualquer loading".
 */
USTRUCT(BlueprintType)
struct FZMMOLoadingTipRow : public FTableRowBase
{
	GENERATED_BODY()

	/** Texto da dica (localizável). */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Loading")
	FText Tip;

	/** Restringe a dica a um contexto. None = todos. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Loading")
	EZMMOLoadingContext Context = EZMMOLoadingContext::None;

	/** Tag opcional pra categorizar (PvE/PvP/Crafting...) — futuro filtro. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Loading")
	FGameplayTag Category;
};
