#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "UI/ThemeKeys.h"
#include "UI/ThemeRow.h"
#include "ZeusThemeDataAsset.generated.h"

UCLASS(BlueprintType)
class ZMMO_API UZeusThemeDataAsset : public UPrimaryDataAsset
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Theme")
	FName ThemeId;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Theme")
	FText DisplayName;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Theme", meta = (ToolTip = "Only fill the keys this theme overrides. Missing keys fall back to the Default theme."))
	TMap<EZeusThemeKey, FThemeEntry> Entries;

	bool HasKey(EZeusThemeKey Key) const;
	const FThemeEntry* FindEntry(EZeusThemeKey Key) const;
};
