#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"
#include "DialogRow.generated.h"

USTRUCT(BlueprintType)
struct ZMMO_API FDialogChoice
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Dialog")
	FText Text;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Dialog")
	FName NextNode;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Dialog")
	FName RequiredQuestState;
};

USTRUCT(BlueprintType)
struct ZMMO_API FDialogRow : public FTableRowBase
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Dialog", meta = (MultiLine = true))
	FText SpeakerLine;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Dialog")
	TArray<FDialogChoice> Choices;
};
