#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"
#include "Players/StatBlock.h"
#include "ClassRow.generated.h"

class APawn;

USTRUCT(BlueprintType)
struct ZMMO_API FClassRow : public FTableRowBase
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Class")
	FText DisplayName;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Class")
	TSoftClassPtr<APawn> BlueprintRef;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Stats")
	FStatBlock BaseStats;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Stats")
	FStatBlock LevelUpStats;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Class")
	TArray<FName> StartingAbilities;
};
