#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"
#include "ThemeCalendarRow.generated.h"

USTRUCT(BlueprintType)
struct ZMMO_API FThemeCalendarRow : public FTableRowBase
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Calendar")
	FName ThemeId;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Calendar", meta = (ClampMin = "1", ClampMax = "12"))
	int32 StartMonth = 1;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Calendar", meta = (ClampMin = "1", ClampMax = "31"))
	int32 StartDay = 1;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Calendar", meta = (ClampMin = "1", ClampMax = "12"))
	int32 EndMonth = 12;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Calendar", meta = (ClampMin = "1", ClampMax = "31"))
	int32 EndDay = 31;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Calendar", meta = (ToolTip = "Higher priority wins when ranges overlap."))
	int32 Priority = 0;
};
